// Mocks generated by Mockito 5.4.6 from annotations
// in rick_montry_pit_test/test/features/character/data/repositories/character_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rick_montry_pit_test/core/network/network_info.dart' as _i7;
import 'package:rick_montry_pit_test/features/character/data/datasources/character_local_data_source.dart'
    as _i5;
import 'package:rick_montry_pit_test/features/character/data/datasources/character_override_local_data_source.dart'
    as _i6;
import 'package:rick_montry_pit_test/features/character/data/datasources/character_remote_data_source.dart'
    as _i2;
import 'package:rick_montry_pit_test/features/character/data/models/character_model.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CharacterRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacterRemoteDataSource extends _i1.Mock
    implements _i2.CharacterRemoteDataSource {
  MockCharacterRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CharacterModel>> getAllCharacters(
    int? page, {
    String? name,
    String? status,
    String? species,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAllCharacters,
              [page],
              {#name: name, #status: status, #species: species},
            ),
            returnValue: _i3.Future<List<_i4.CharacterModel>>.value(
              <_i4.CharacterModel>[],
            ),
          )
          as _i3.Future<List<_i4.CharacterModel>>);
}

/// A class which mocks [CharacterLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacterLocalDataSource extends _i1.Mock
    implements _i5.CharacterLocalDataSource {
  MockCharacterLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CharacterModel>> getLastCharacters() =>
      (super.noSuchMethod(
            Invocation.method(#getLastCharacters, []),
            returnValue: _i3.Future<List<_i4.CharacterModel>>.value(
              <_i4.CharacterModel>[],
            ),
          )
          as _i3.Future<List<_i4.CharacterModel>>);

  @override
  _i3.Future<void> cacheCharacters(
    List<_i4.CharacterModel>? charactersToCache,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheCharacters, [charactersToCache]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [CharacterOverrideLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacterOverrideLocalDataSource extends _i1.Mock
    implements _i6.CharacterOverrideLocalDataSource {
  MockCharacterOverrideLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveOverride(_i4.CharacterModel? character) =>
      (super.noSuchMethod(
            Invocation.method(#saveOverride, [character]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i4.CharacterModel? getOverride(int? id) =>
      (super.noSuchMethod(Invocation.method(#getOverride, [id]))
          as _i4.CharacterModel?);

  @override
  bool hasOverride(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#hasOverride, [id]),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<void> deleteOverride(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOverride, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
